In [2]:
import numpy as np
import pandas
from tabulate import tabulate

# # Импорт библиотек

In [3]:
matrix_1 = np.array([[1, 2, 3], [3, 2, 1]]) # Первая матрица
matrix_2 = np.array([[0, 2], [1, -1],[0, 1]]) # Вторая матрица

# # Умножение матриц


In [4]:
print(np.dot (matrix_1, matrix_2)) # Результат умножения матрицы
print(np.dot (matrix_2, matrix_1)) # Результат умножения матрицы

[[2 3]
 [2 5]]
[[ 6  4  2]
 [-2  0  2]
 [ 3  2  1]]


# # Свойства матриц

In [5]:
# Ассоциативность - это (AB)C = A(BC) то есть порядок умножения не влияет на результат
matrix_A = np.array([[1, 2], [3, 4]])
matrix_B = np.array([[5, 6], [7, 8]])
matrix_C = np.array([[9, 10], [11, 12]])
result_1 = np.dot(np.dot(matrix_A, matrix_B), matrix_C)
result_2 = np.dot(matrix_A, np.dot(matrix_B, matrix_C))
print("Ассоциативность:", np.array_equal(result_1, result_2))

Ассоциативность: True


# # Произведение Адамара

In [6]:
# Произведение Адамара - это поэлементное умножение матриц одинакового размера
matrix_X = np.array([[1, 2, 3], [4, 5, 6]])
matrix_Y = np.array([[7, 8, 9], [10, 11, 12]])
hadamard_product = np.multiply(matrix_X, matrix_Y)
print("Произведение Адамара:\n", hadamard_product)

Произведение Адамара:
 [[ 7 16 27]
 [40 55 72]]


# # Обращение и транспонирование матриц

In [7]:
# Обращение - это нахождение обратной матрицы ( произведение матрицы на обратную дает единичную матрицу)
# Транспонирование - это замена строк на столбцы и наоборот
matrix_A = np.array([[1, 2], [3, 4]])
inverse_A = np.linalg.inv(matrix_A)
transpose_A = np.transpose(matrix_A)
print("Искомая матрица A:")
print(tabulate(matrix_A, tablefmt="grid"))
print("Обратная матрица A:")
print(tabulate(inverse_A, tablefmt="grid"))
print("Транспонированная матрица A:")
print(tabulate(transpose_A, tablefmt="grid"))


Искомая матрица A:
+---+---+
| 1 | 2 |
+---+---+
| 3 | 4 |
+---+---+
Обратная матрица A:
+------+------+
| -2   |  1   |
+------+------+
|  1.5 | -0.5 |
+------+------+
Транспонированная матрица A:
+---+---+
| 1 | 3 |
+---+---+
| 2 | 4 |
+---+---+


# # Запись систем линейных уравнений в матричной форме

In [15]:
# Рассмотрим систему линейных уравнений:
# 2x1 + 3x2 + 5x3 = 1
# 4x1 - 2x2 - 7x3 = 8
# 9x1 + 5x2 - 3x3 = 2
A = np.array([[2, 3, 5], [4, -2, -7], [9, 5, -3]])
B = np.array([1, 8, 2])
# Запишем систему в матричной форме AX = B
# где A - матрица коэффициентов, X - вектор неизвестных, B - вектор свободных членов
# А сама матрица СЛУ будет выглядеть так:
augmented_matrix = np.hstack((A, B.reshape(-1, 1)))
print("Расширенная матрица системы уравнений:")
# Первая матрица - это матрица коэффициентов, вторая - вектор свободных членов а третья - решение системы
print(tabulate(augmented_matrix, tablefmt="grid", headers=["Coef1", "Coef2", "Coef3", "FreeTerm"]))

Расширенная матрица системы уравнений:
+---------+---------+---------+------------+
|   Coef1 |   Coef2 |   Coef3 |   FreeTerm |
+=========+=========+=========+============+
|       2 |       3 |       5 |          1 |
+---------+---------+---------+------------+
|       4 |      -2 |      -7 |          8 |
+---------+---------+---------+------------+
|       9 |       5 |      -3 |          2 |
+---------+---------+---------+------------+


# # Решение СЛУ методом Гаусса

In [17]:
# Матрица коэффициентов (без столбца свободных членов)
matrix_A1 = np.array([[2, 3, 5], [4, -2, -7], [9, 5, -3]], dtype=float)
# Вектор свободных членов
matrix_B1 = np.array([1, 8, 2], dtype=float)

# Решение системы уравнений методом Гаусса
x = np.linalg.solve(matrix_A1, matrix_B1)
print("Решение системы уравнений:")
print(tabulate(x.reshape(-1, 1), tablefmt="grid", headers=["X"]))


Решение системы уравнений:
+----------+
|        X |
+==========+
|  2.44538 |
+----------+
| -3.28571 |
+----------+
|  1.19328 |
+----------+
